version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: >
      mysqld --default-authentication-plugin=mysql_native_password
    platform: linux/x86_64
    volumes:
      - mysql-data:/var/lib/mysql
  python:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    platform: linux/x86_64

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    environment:
      PMA_HOST: 'db'
      PMA_USER: 'user'
      PMA_PASSWORD: 'password'
    ports:
      - '${PHP_MY_ADMIN_PORT:-}:80'
    depends_on:
      - db

volumes:
  mysql-data:
    driver: local